// lorem text
const text = [
  `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
  `Sed ac felis mollis tellus vulputate feugiat. Pellentesque vitae ipsum id arcu luctus sollicitudin at et lacus. Sed id mattis ante. Nulla egestas dignissim nisi, sit amet feugiat tellus rutrum in. Fusce auctor nisl ac elementum vulputate. Proin porttitor faucibus libero, tempus tempor mi elementum at. Duis dictum nisl eu augue sagittis elementum sit amet vitae metus. Nam sed metus et diam mollis bibendum eget quis sapien. Suspendisse sed ornare metus, eget vehicula dui. Sed interdum augue quis est varius pretium. Morbi in nunc consequat, vehicula arcu in, volutpat lorem. Vestibulum maximus efficitur nisl feugiat pretium. Morbi sit amet ornare nulla, quis tincidunt nisi. Suspendisse luctus leo tellus, non luctus sapien consectetur ac. Nullam ut turpis et eros faucibus ornare. Etiam tincidunt mauris sit amet ante egestas, a ullamcorper nibh euismod.`,
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in dapibus arcu. Morbi iaculis aliquet enim, eget fringilla eros lacinia in. Pellentesque pharetra, metus vitae suscipit eleifend, ex lorem hendrerit ante, vitae luctus erat libero id risus. Praesent eget ligula dapibus, porttitor tortor id, pulvinar leo. In hac habitasse platea dictumst. Vestibulum nec dui et ligula blandit dictum at vitae velit. Morbi ornare tempor tortor vitae laoreet. Vivamus et nunc non massa tristique ullamcorper ut et elit. Aenean sit amet tortor ut nisl volutpat pharetra sit amet et diam.`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
Etiam augue ipsum, aliquam a lobortis vitae, iaculis at mi. Mauris nisi nisi, euismod eu molestie ut, semper eget nulla. Phasellus ultricies tristique dolor, vel interdum justo lobortis vel. Maecenas fermentum lacus lectus, eget viverra nibh fringilla vitae. Morbi sollicitudin vulputate sapien, ac volutpat dolor volutpat nec. In hac habitasse platea dictumst. Vestibulum sed mauris et sem facilisis fermentum sit amet a tortor. Nulla quis consequat lacus. Proin maximus auctor purus, vel imperdiet mi rhoncus vel. Cras iaculis lacus in massa mattis, et imperdiet ipsum varius. Donec diam lorem, efficitur at est varius, blandit porta lacus. Cras pellentesque nunc mauris, nec consectetur sapien iaculis a. Sed ultrices ante non nibh interdum fermentum. Sed quis neque commodo, bibendum justo ac, imperdiet nisi. Nunc lacinia quam pellentesque odio porta pellentesque.`,
  `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
  `Maecenas pellentesque dolor metus, sed pellentesque mi tincidunt at. Pellentesque id nisl ut lacus condimentum aliquet. Nunc sodales diam sit amet velit fringilla, vel aliquet arcu sodales. Etiam eros ipsum, iaculis eu urna a, auctor vehicula leo. Aliquam at ipsum id nibh volutpat convallis. Nullam blandit tortor turpis, eget aliquam metus lacinia eu. Integer a dui quis erat efficitur pharetra. Aliquam ultricies bibendum nisl ut imperdiet. Nunc magna ligula, maximus in libero sit amet, pulvinar efficitur nisi. Pellentesque dictum neque sit amet egestas vehicula.`,
  `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
];

    
    const form = document.querySelector(".lorem-form");
    const words = document.getElementById("words");
    const result = document.querySelector(".lorem-text");
    
form.addEventListener("submit", loremIpsum)

  function loremIpsum(e) {
    // A click on a form submit button – initiates its submission to the server.
    
    
  };
